---
title: "Instructions on How to Use the xrfr Package"
output: html_document
author: Anna Grytaas
date: "`r Sys.Date()`"
---

This R package was created to convert elemental composition x-ray fluorescence (XRF) data of filtrated water samples from kcps to µM. 

## The files

First, you have to make sure to have the right files, and that these are all in the same folder on your computer. There are three files you need for your analysis: 

* A file with **raw data** from the XRF machine.
* A file with **information about the samples and project**, like which location the samples are from, whether they are blank samples, and the volume of the filtrated water.
* A file containing **information about the machine, filters and elements**, like crystal drift and calibrated constants.

### The raw data file

This file is created by the XRF machine when you export your data from it. You should not edit this file unless there are errors in the sample names. This file will be a .txt file using comma (,) as a decimal mark and tabs to separate columns. It will contain a column named **"Sample"**, a column named **"Date"**, and several columns with results from the machine's analysis. The ones we are interested in in this case are those with "(Int)" behind the element. 

### The project information file

This file should contain all relevant information that you wish to include about your data that is not from the XRF machine. There are several columns that must be included for the functions in this package to work:

* **"Sample"**: The name of your sample. Must be the same as in the raw data file. Any samples that do not match exactly will not be included in the created file. 
* **"Filter_type"**: The type of filter used when filtering. Can be PC, ANO, or GFF. This column must be filled out even if the same filter type was used on all samples because R needs to know which detection limits and calibrated constants to use. 
* **"Filter_size"**: The pore size of the filter used. This column can be left empty if the size was the same in all filters, but the column must exist. 
* **"Filter_box_nr"**: Let's R know which box the filter came from so it knows which blank samples to apply when finding the net count in this sample. 
* **Filter_blank**: In this column you will need to write "blank" for all your blank samples.
* **Volume**: The volume of water that was filtered. 

You may include as many more columns as you want, for example dates, depth, or station, but these columns all need to be present in your project information file. 

### The "setup" file

This file must contain all the relevant information related to the XRF machine, filters, and elements. This is a file that will not change between experiments unless the crystal drift has been measured again. The "setup" file must contain these columns:

* **Element**: All the elements measured by the machine. 
* **MolarW**: The molar weight of each element. 
* **PC**, **ANO**, and **GFF**: The calibrated constant for each element for each of the three filter types. Must be in this order. 
* **DL_PC**, **DL_ANO**, and **DL_GFF**: The detection limit of each element for each of the three filter types. Must be in this order. 
* **Drift_2008**, **Drift_2010**, etc.: The crystal drift each year it was measured. 2008 was the first year this was measured on the XRF machine at UiB, so this is used during the calculations. 

## New to R/RStudio?

*You can skip this part if you are familiar with R/RStudio and R packages.*

Both R and Rstudio can be downloaded to your computer for free from the internet. R is available at https://cran.r-project.org/ and Rstudio at https://rstudio.com/products/rstudio/download/. R is a language and environment used for statistical computing and graphics, while RStudio is an integrated development environment for R. This means that RStudio uses the R language and environment, but also gives you the possibility to keep and come back to your code, easy access to for example dataframes and plots, etc. 

### Getting started

Once you have both R and RStudio installed, open RStudio. At this point you need to tell R where to look for files and save new files to. This can be done by manually setting the work directory using `setwd()` or *Session* &rarr; *Set Working Directory* &rarr; *Choose Directory...*, or by creating a project (recommended). To create a project you can click *File* &rarr; *New Project...* or the "R within a box"-icon with a plus in a green circle at the top left. You can use an existing folder (where your project files are saved) as a directory by clicking *Existing Directory*. If you choose to click *New Directory*, you will need to move the project files to this folder. You then choose the project name and where to put it, click *Create Project*, and you are ready to start coding. Next time you want to work on this code, open the .Rproj file in your directory, and it will open exactly as you left it. 

### Need help?

Before even starting, it is useful to know how to get help if you have problems in R/RStudio. In the bottom right window in RStudio, where you can see the files in your directory, you can go to the tab "Help" and search for specific functions to learn how they work. This can also be accessed by running the code `help("name_of_function")`, for example `help("summarise")`. Some functions have further information available in vignettes, which can be accessed via the code `vignette("name_of_function")`, for example `vignette("nest")`. Information about packages can be accessed by using the code `help(package = "name_of_package")`, for example `help(package = "ggplot2")`. This information and more is always available on the internet as well, and you can find it by searching for the function or package. In addition, a lot of the most used packages have cheat sheets available at https://rstudio.com/resources/cheatsheets/, and on https://stackoverflow.com/ you can browse through other people's questions or ask your own. There are also many guides available for free on how to use R/Rstudio, for example this one for people who are used to Excel: https://rstudio-conf-2020.github.io/r-for-excel/. 

### R packages

R packages are extensions to R that can be installed. There are many packages available, and some of the most popular ones are very useful to have. The group of packages called **tidyverse** is especially useful and one you will likely need if you plan on handling data or creating graphics with R. It includes packages such as **dplyr** (to manipulate data), **tidyr** (to help create tidy data), and **ggplot2** (to create graphics). The package **readxl** is useful if you want to import Excel files (.xlsx og .xls). Packages can be installed via the code `install.packages("name_of_package")`, for example `install.packages("tidyverse")`. Once you have installed a package, you need to let R know that you wish to use functions from it. This is done with the function `library()`, for example `library(dplyr)`. 

### Some tips

- To run a line of code from your R Script you press ctrl + enter (on Windows or Linux) or cmd + enter (on Mac). You can also press run at the top right in the toolbar. 
- Using pipe operators make your code more readable and tidier. They are written as `%>%`. The pipe operator is a part of the **magrittr** package, but are also used in the **dplyr** package that you will likely be using (by running `library(dplyr)` or `library(tidyverse)`). On Windows or Linux you can use ctrl + shift + M as a shortcut for the pipe, and on Mac this is cmd + shift + M. `y %>% x` = `x(y)`. 
- Use # at the beginning of a line to create a comment. Comments are ignored by R when running the code. This way you can write comments explaining what a function does etc. 

## Using the xrfr package

### Installing

If it is your first time using it, you need to install the package before you can use it. To do this, you must use the function `install_github()` from the **remotes** package. This package is a part of the **devtools** group of packages. If you do not already have this installed, you need to install either the **devtools** group of packages or only the **remotes** package first, by using the `install.packages()` function (`install.packages("remotes")` or `install.packages("devtools")`). To install the xrfr package you then run the code `install_github("agryt/xrfr")`. 

### Preparing your data

Before starting the analysis, make sure that your files are properly formatted with the right column names and matching sample names. Your code will not work and you may get warning messages if they are not. 

Before you can use the **xrfr** functions, you must import your data to RStudio. How this is done depends on which format your files are saved in. Your raw data file is created as a .txt file by the XRF computer, so this is likely how yours will be saved. If so, using the code `read_delim("your_raw_data.txt", delim = "\t", locale = locale(decimal_mark = ","))` should work, as long as the **readr** package (or the whole **tidyverse** package) is loaded using the `library()` function. Excel files can be imported using the `read_excel()` function from the **readxl** package, and CSV files can be imported using the `read_csv()` or `read_csv2()` functions from the **readr** package depending on which type of CSV file it is. If you are using other file formats, you can use your search engine to find out how to import them, as it is likely possible to do so. 

Here is an example of how to import the files:

```{r data import, eval = FALSE}

library(tidyverse) # includes readr, which is needed here
library(readxl)

rawdata.df <- read_delim("xrf_rawdata.txt", delim = "\t", locale = locale(decimal_mark = ","))
projectinfo.df <- read_excel("xrf_projectinfo.xlsx")
setup.df <- read_excel("xrf_setup.xlsx")

```


